CREATE TABLE roles (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(50) NOT NULL UNIQUE,
    description VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);


INSERT INTO roles (name, description) VALUES ('CLIENT', 'Utilisateur standard de la plateforme');
INSERT INTO roles (name, description) VALUES ('ADMIN', 'Administrateur de la plateforme EventSphere');

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    phone VARCHAR2(30),
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0,1)),
    last_login TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT pk_users PRIMARY KEY (id)
);


DESC users;


INSERT INTO users (first_name, last_name, email, password, phone)
VALUES ('Admin', 'EventSphere', 'admin@eventsphere.com', 'admin123', '0600000000');

INSERT INTO users (first_name, last_name, email, password, phone)
VALUES ('Client', 'Test', 'client@test.com', 'client123', '0611111111');


CREATE TABLE user_roles (
    user_id NUMBER NOT NULL,
    role_id NUMBER NOT NULL,
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

-- Admin
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u, roles r
WHERE u.email = 'admin@eventsphere.com'
  AND r.name = 'ADMIN';

-- Client
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u, roles r
WHERE u.email = 'client@test.com'
  AND r.name = 'CLIENT';
  
  CREATE TABLE categories (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(100) NOT NULL UNIQUE,
    description VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);


INSERT INTO categories (name, description)
VALUES ('Conférence', 'Conférences professionnelles et métiers');

INSERT INTO categories (name, description)
VALUES ('Formation', 'Formations certifiantes et professionnelles');

INSERT INTO categories (name, description)
VALUES ('Séminaire', 'Séminaires d’entreprise et management');

INSERT INTO categories (name, description)
VALUES ('Atelier', 'Ateliers pratiques et techniques');

INSERT INTO categories (name, description)
VALUES ('Salon', 'Salons professionnels et spécialisés');

INSERT INTO categories (name, description)
VALUES ('Culture', 'Événements culturels à thème');


CREATE TABLE events (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    title VARCHAR2(200) NOT NULL,
    description CLOB NOT NULL,
    objective VARCHAR2(255),
    category_id NUMBER NOT NULL,
    organizer_id NUMBER NOT NULL,
    location VARCHAR2(200),
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    capacity NUMBER NOT NULL CHECK (capacity > 0),
    reserved_places NUMBER DEFAULT 0 CHECK (reserved_places >= 0),
    image_url VARCHAR2(255),
    status VARCHAR2(20) DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'COMPLETED', 'CANCELLED')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT pk_events PRIMARY KEY (id),
    CONSTRAINT fk_event_category FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT fk_event_organizer FOREIGN KEY (organizer_id) REFERENCES users(id)
);


INSERT INTO events (
    title, description, objective, category_id, organizer_id,
    location, start_date, end_date, capacity, image_url
)
SELECT
    'L’avenir de l’intelligence artificielle en entreprise',
    'Conférence dédiée aux décideurs pour comprendre les enjeux, opportunités et risques liés à l’IA en entreprise.',
    'Sensibiliser les professionnels à l’IA',
    c.id,
    u.id,
    'Paris – La Défense',
    TIMESTAMP '2025-03-15 09:00:00',
    TIMESTAMP '2025-03-15 17:00:00',
    300,
    '/uploads/events/ai-conference.jpg'
FROM categories c, users u
WHERE c.name = 'Conférence'
  AND u.email = 'admin@eventsphere.com';


CREATE TABLE event_images (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    event_id NUMBER NOT NULL,
    image_url VARCHAR2(255) NOT NULL,
    is_primary NUMBER(1) DEFAULT 0 CHECK (is_primary IN (0,1)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_event_images PRIMARY KEY (id),
    CONSTRAINT fk_event_images_event
        FOREIGN KEY (event_id)
        REFERENCES events(id)
        ON DELETE CASCADE
);


INSERT INTO event_images (event_id, image_url, is_primary)
SELECT id, '/uploads/events/ai-conference-2.jpg', 0
FROM events
WHERE title = 'L’avenir de l’intelligence artificielle en entreprise';


CREATE TABLE reservations (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id NUMBER NOT NULL,
    event_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL CHECK (quantity > 0),
    status VARCHAR2(20) DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'CANCELLED', 'EXPIRED')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    cancelled_at TIMESTAMP,
    CONSTRAINT pk_reservations PRIMARY KEY (id),
    CONSTRAINT fk_res_user FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_res_event FOREIGN KEY (event_id)
        REFERENCES events(id)
        ON DELETE CASCADE
);


INSERT INTO reservations (user_id, event_id, quantity)
SELECT 
    u.id,
    e.id,
    2
FROM users u, events e
WHERE u.email = 'client@test.com'
  AND e.title = 'L’avenir de l’intelligence artificielle en entreprise';
  
UPDATE events
SET reserved_places = reserved_places + 2
WHERE title = 'L’avenir de l’intelligence artificielle en entreprise';

CREATE TABLE notifications (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id NUMBER NOT NULL,
    title VARCHAR2(150) NOT NULL,
    message VARCHAR2(500) NOT NULL,
    type VARCHAR2(30),
    related_event_id NUMBER,
    is_read NUMBER(1) DEFAULT 0 CHECK (is_read IN (0,1)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_notifications PRIMARY KEY (id),
    CONSTRAINT fk_notif_user FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_notif_event FOREIGN KEY (related_event_id)
        REFERENCES events(id)
        ON DELETE SET NULL
);



INSERT INTO notifications (
    user_id, title, message, type, related_event_id
)
SELECT
    u.id,
    'Confirmation de réservation',
    'Votre réservation a été confirmée avec succès.',
    'RESERVATION',
    e.id
FROM users u, events e
WHERE u.email = 'client@test.com'
  AND e.title = 'L’avenir de l’intelligence artificielle en entreprise';


CREATE TABLE favorites (
    user_id NUMBER NOT NULL,
    event_id NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_favorites PRIMARY KEY (user_id, event_id),
    CONSTRAINT fk_fav_user FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_fav_event FOREIGN KEY (event_id)
        REFERENCES events(id)
        ON DELETE CASCADE
);


INSERT INTO favorites (user_id, event_id)
SELECT 
    u.id,
    e.id
FROM users u, events e
WHERE u.email = 'client@test.com'
  AND e.title = 'Atelier pratique Node.js & API REST sécurisées';


CREATE TABLE event_views (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    event_id NUMBER NOT NULL,
    user_id NUMBER,
    viewer_ip VARCHAR2(50),
    viewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_event_views PRIMARY KEY (id),
    CONSTRAINT fk_ev_event FOREIGN KEY (event_id)
        REFERENCES events(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_ev_user FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE SET NULL
);



CREATE TABLE tickets (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id NUMBER NOT NULL,
    subject VARCHAR2(200) NOT NULL,
    type VARCHAR2(50),
    status VARCHAR2(20) DEFAULT 'OPEN'
        CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP,
    CONSTRAINT pk_tickets PRIMARY KEY (id),
    CONSTRAINT fk_ticket_user FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);


CREATE TABLE ticket_messages (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ticket_id NUMBER NOT NULL,
    sender_id NUMBER NOT NULL,
    message CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ticket_messages PRIMARY KEY (id),
    CONSTRAINT fk_tm_ticket FOREIGN KEY (ticket_id)
        REFERENCES tickets(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_tm_sender FOREIGN KEY (sender_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);


CREATE TABLE audit_logs (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id NUMBER,
    action VARCHAR2(100) NOT NULL,
    entity_type VARCHAR2(50),
    entity_id NUMBER,
    description VARCHAR2(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id),
    CONSTRAINT fk_audit_user FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE SET NULL
);

ALTER TABLE EVENTS
ADD PRICE_INCLUDES VARCHAR2(500);


ALTER TABLE EVENTS ADD PRICE NUMBER;
ALTER TABLE EVENTS MODIFY PRICE DEFAULT 0;

ALTER TABLE EVENTS MODIFY PRICE NOT NULL;

DESC EVENTS;

-- =========================================
-- PAYMENTS TABLE (Fake payment)
-- =========================================

-- 1) Create table
CREATE TABLE PAYMENTS (
  ID         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  USER_ID    NUMBER NOT NULL,
  EVENT_ID   NUMBER NOT NULL,
  AMOUNT     NUMBER(10,2) NOT NULL,
  STATUS     VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT PK_PAYMENTS PRIMARY KEY (ID),

  -- Adjust referenced table name if yours is USERS / APP_USERS / UTILISATEURS, etc.
  CONSTRAINT FK_PAYMENTS_USER
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),

  CONSTRAINT FK_PAYMENTS_EVENT
    FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(ID),

  CONSTRAINT CK_PAYMENTS_AMOUNT
    CHECK (AMOUNT >= 0),

  CONSTRAINT CK_PAYMENTS_STATUS
    CHECK (STATUS IN ('PENDING', 'PAID', 'FAILED', 'CANCELED'))
);

-- 2) Useful indexes (recommended)
CREATE INDEX IDX_PAYMENTS_USER_ID ON PAYMENTS (USER_ID);
CREATE INDEX IDX_PAYMENTS_EVENT_ID ON PAYMENTS (EVENT_ID);
CREATE INDEX IDX_PAYMENTS_STATUS ON PAYMENTS (STATUS);

-- 3) Optional: prevent duplicate "PAID" for same user+event (keep only 1 successful payment)
-- If you want multiple attempts allowed, keep this commented.
-- CREATE UNIQUE INDEX UQ_PAYMENTS_USER_EVENT_PAID
--   ON PAYMENTS (USER_ID, EVENT_ID, CASE WHEN STATUS='PAID' THEN 1 ELSE NULL END);

UPDATE users
SET password = '$2b$10$x64tcVJgC6OKSUe0LRsdJ.vtrWhnkss.XXQ/bIPv7czEbW4LWFIKS'
WHERE email = 'admin@eventsphere.com';

COMMIT;